import type { ProjectWorkspace, SourceSet } from './types'

export const SOURCE_SETS: SourceSet[] = [
  {
    id: 'source-set-agile-risk',
    name: 'Agile Risk Evidence Pack',
    description: 'Instructor-curated sources for communication, sprint feedback, and agile risk claims.',
    tags: ['Agile', 'Risk', 'Communication'],
    visibility: 'Shared',
    ownerName: 'Instructor',
    sharedProjectIds: ['agile-risk-project'],
    sources: [
      {
        id: 'instructor-source-1',
        title: 'instructor-agile-risk-framework.pdf',
        type: 'PDF',
        status: 'Ready',
        excerpt: 'Risk control improves when agile teams define escalation paths, feedback cadence, and decision ownership.',
        owner: 'instructor',
        sourceSetId: 'source-set-agile-risk',
        sharedBy: 'Instructor',
        themes: ['risk control', 'communication protocol'],
      },
      {
        id: 'instructor-source-2',
        title: 'feedback-loop-benchmark.docx',
        type: 'DOCX',
        status: 'Ready',
        excerpt: 'Teams with structured sprint feedback loops identify blockers earlier than teams relying on informal updates.',
        owner: 'instructor',
        sourceSetId: 'source-set-agile-risk',
        sharedBy: 'Instructor',
        themes: ['feedback loops', 'blocker discovery'],
      },
    ],
  },
  {
    id: 'source-set-review-methods',
    name: 'Software Review Methods',
    description: 'Private instructor collection for future projects about peer review and evidence quality.',
    tags: ['Review', 'Evidence Quality'],
    visibility: 'Private',
    ownerName: 'Instructor',
    sharedProjectIds: [],
    sources: [
      {
        id: 'instructor-source-3',
        title: 'software-review-rubric.pdf',
        type: 'PDF',
        status: 'Ready',
        excerpt: 'Review rubrics improve feedback consistency by separating claim clarity, evidence strength, and writing quality.',
        owner: 'instructor',
        sourceSetId: 'source-set-review-methods',
        sharedBy: 'Instructor',
        themes: ['review rubric', 'feedback quality'],
      },
    ],
  },
]

export const PROJECTS: ProjectWorkspace[] = [
  {
    id: 'agile-risk-project',
    title: 'Managing Risk and Communication in Agile Software Projects',
    description: 'Student draft returned with instructor feedback about evidence strength and claim clarity.',
    status: 'Returned with Feedback',
    reviewStatus: 'Ready for Review',
    studentName: 'Minh Nguyen',
    documentCount: 3,
    claimCount: 4,
    supportedClaimCount: 2,
    feedbackCount: 2,
    isEmpty: false,
    paragraphs: [
      'Agile software development depends on fast communication between stakeholders, product owners, and delivery teams. However, project risk increases when feedback loops are informal or delayed.',
      'Clear communication protocols reduce project risk because teams can identify blockers earlier and align decisions before sprint goals are missed.',
      'Risk management in agile projects should combine lightweight documentation, frequent review meetings, and traceable evidence for important project claims.',
      'Some teams assume daily meetings alone are enough to control project uncertainty, but this claim still needs stronger evidence from the uploaded sources.',
    ],
    sources: [
      {
        id: 'source-1',
        title: 'agile-risk-management.pdf',
        type: 'PDF',
        status: 'Ready',
        excerpt: 'Structured communication practices improve stakeholder alignment and reduce unresolved delivery risks in agile teams.',
      },
      {
        id: 'source-2',
        title: 'sprint-review-feedback.docx',
        type: 'DOCX',
        status: 'Ready',
        excerpt: 'Rapid feedback loops help teams discover blockers early and adjust sprint scope before project risk grows.',
      },
      {
        id: 'source-3',
        title: 'https://example.com/agile-evidence-map',
        type: 'Link',
        status: 'Ready',
        excerpt: 'Evidence traceability links project claims to source material so reviewers can evaluate support quality.',
      },
      {
        id: 'source-4',
        title: 'stakeholder-alignment-study.pdf',
        type: 'PDF',
        status: 'Ready',
        excerpt: 'Stakeholder alignment improves when teams document decision rationale and revisit risk assumptions during reviews.',
      },
      {
        id: 'source-5',
        title: 'communication-patterns-review.docx',
        type: 'DOCX',
        status: 'Ready',
        excerpt: 'Communication patterns across agile ceremonies influence how quickly evidence gaps and project risks are discovered.',
      },
    ],
    claims: [
      {
        id: 'claim-communication-risk',
        text: 'Clear communication protocols reduce project risk',
        supported: true,
        paragraphIndex: 1,
      },
      {
        id: 'claim-traceable-evidence',
        text: 'traceable evidence for important project claims',
        supported: true,
        paragraphIndex: 2,
      },
      {
        id: 'claim-daily-meetings',
        text: 'daily meetings alone are enough to control project uncertainty',
        supported: false,
        paragraphIndex: 3,
      },
      {
        id: 'claim-feedback-loops',
        text: 'teams can identify blockers earlier',
        supported: false,
        paragraphIndex: 1,
      },
    ],
    evidenceResults: [
      {
        id: 'evidence-1',
        sourceId: 'source-1',
        claimId: 'claim-communication-risk',
        excerpt: 'Structured communication practices improve stakeholder alignment and reduce unresolved delivery risks in agile teams.',
        match: 91,
        status: 'mapped',
      },
      {
        id: 'evidence-2',
        sourceId: 'source-2',
        claimId: 'claim-communication-risk',
        excerpt: 'Rapid feedback loops help teams discover blockers early and adjust sprint scope before project risk grows.',
        match: 84,
        status: 'suggested',
      },
      {
        id: 'evidence-3',
        sourceId: 'source-3',
        claimId: 'claim-traceable-evidence',
        excerpt: 'Evidence traceability links project claims to source material so reviewers can evaluate support quality.',
        match: 88,
        status: 'mapped',
      },
      {
        id: 'evidence-4',
        sourceId: 'source-2',
        claimId: 'claim-feedback-loops',
        excerpt: 'Rapid feedback loops help teams discover blockers early and adjust sprint scope before project risk grows.',
        match: 82,
        status: 'suggested',
      },
      {
        id: 'evidence-5',
        sourceId: 'source-4',
        claimId: 'claim-communication-risk',
        excerpt: 'Stakeholder alignment improves when teams document decision rationale and revisit risk assumptions during reviews.',
        match: 86,
        status: 'suggested',
      },
      {
        id: 'evidence-6',
        sourceId: 'source-5',
        claimId: 'claim-traceable-evidence',
        excerpt: 'Communication patterns across agile ceremonies influence how quickly evidence gaps and project risks are discovered.',
        match: 80,
        status: 'suggested',
      },
    ],
    comments: [
      {
        id: 'comment-1',
        target: 'claim',
        claimId: 'claim-communication-risk',
        quote: 'Clear communication protocols reduce project risk',
        author: 'Instructor',
        body: 'Good claim, but explain which communication protocol is most relevant to agile risk control.',
        category: 'Claim clarity',
        resolved: false,
      },
      {
        id: 'comment-2',
        target: 'text',
        quote: 'daily meetings alone are enough',
        author: 'Instructor',
        body: 'This sentence is too broad. Add a source or revise the claim to be less absolute.',
        category: 'Evidence strength',
        resolved: false,
      },
    ],
    graphNodes: [
      { id: 'claim-communication-risk', label: 'Communication protocols reduce risk', kind: 'claim' },
      { id: 'source-1', label: 'agile-risk-management.pdf', kind: 'source' },
      { id: 'source-2', label: 'sprint-review-feedback.docx', kind: 'source' },
      { id: 'claim-feedback-loops', label: 'Feedback loops identify blockers', kind: 'related-claim' },
    ],
    graphEdges: [
      { id: 'edge-1', from: 'claim-communication-risk', to: 'source-1', label: 'mapped evidence', strength: 'strong' },
      { id: 'edge-2', from: 'claim-communication-risk', to: 'source-2', label: 'suggested evidence', strength: 'medium' },
      { id: 'edge-3', from: 'claim-communication-risk', to: 'claim-feedback-loops', label: 'related claim', strength: 'weak' },
    ],
    sourceGraphNodes: [
      { id: 'graph-source-1', sourceId: 'source-1', x: 46, y: 40 },
      { id: 'graph-source-2', sourceId: 'source-2', x: 28, y: 58 },
      { id: 'graph-source-3', sourceId: 'source-3', x: 68, y: 62 },
      { id: 'graph-source-4', sourceId: 'source-4', x: 58, y: 28 },
      { id: 'graph-source-5', sourceId: 'source-5', x: 78, y: 42 },
    ],
    sourceGraphEdges: [
      { id: 'source-edge-1', fromSourceId: 'source-1', toSourceId: 'source-2', label: 'shared claim' },
      { id: 'source-edge-2', fromSourceId: 'source-1', toSourceId: 'source-3', label: 'related evidence' },
      { id: 'source-edge-3', fromSourceId: 'source-1', toSourceId: 'source-4', label: 'shared claim' },
      { id: 'source-edge-4', fromSourceId: 'source-1', toSourceId: 'source-5', label: 'same topic' },
      { id: 'source-edge-5', fromSourceId: 'source-2', toSourceId: 'source-4', label: 'same topic' },
      { id: 'source-edge-6', fromSourceId: 'source-3', toSourceId: 'source-5', label: 'related evidence' },
    ],
  },
  {
    id: 'empty-project',
    title: 'New EvidencePilot Project',
    description: 'Start a new project by uploading sources and creating the first claim.',
    status: 'Draft',
    reviewStatus: 'Not submitted',
    studentName: 'Minh Nguyen',
    documentCount: 0,
    claimCount: 0,
    supportedClaimCount: 0,
    feedbackCount: 0,
    isEmpty: true,
    paragraphs: [],
    sources: [],
    claims: [],
    evidenceResults: [],
    comments: [],
    graphNodes: [],
    graphEdges: [],
    sourceGraphNodes: [],
    sourceGraphEdges: [],
  },
]
